baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Muddy Creek Baptist Church'
theme = "alpha-church"

ssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Sermons"
    url = "/sermons"
    weight = 1

  [[menu.main]]
    name = "Preachers"
    url = "/preachers"
    weight = 1

  [[menu.main]]
    name = "Give"
    url = "https://tithe.ly/give?c=657096"
    weight = 5

  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Muddy Creek Baptist Church"
  subtitle = "Powhatan, VA"
  author = "Jeff Beard"
  keywords = ["church", "hugo", "podcast"]
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  #customCSS = ["example.css"]

  [params.favicon]
    sml = "/example16.png"
    med = "/example32.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.podcast]
    title = "Listen to Alpha Church"
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "The files in the podcast are in the public domain."
    image = "img/podcast_cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    feed = " https://soundcloud.com/muddy-creek-baptist/sets/recent-sermons?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing"

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "37.6128"
    longitude = "-78.0610"
    zoom = "18"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

[params.footer]
      copyright = ["(c) 2022 Muddy Creek Baptist Church.",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    #[[params.links]]
      #service = "Twitter"
      #icon = "fa-twitter"
      #icon_pack = "fab"
      #link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "https://www.facebook.com/muddycreekbaptist.org"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "https://soundcloud.com/muddy-creek-baptist/sets/recent-sermons"

    #[[params.links]]
     # service = "Full RSS Feed"
      #icon = "fa-rss"
      #icon_pack = "fas"
      #link = "/index.xml"
