name: GitHub Pages

on: 
  push:
    banches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_tokesn: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          key_files: true
          user_name: fhardison1
          user_email: fhardison+@gmail.com
          publish_branch: main
